'use strict';
let reverseTimer=null,reversePlaying=false,reverseFrames=[],reverseIndex=0;
const re=id=>document.getElementById('reverse-'+id);
function stopReverseAnimation(){clearTimeout(reverseTimer);reverseTimer=null;reversePlaying=false;if(re('play'))re('play').textContent='▶ 播放動畫'}
function reversePanel(){return `<section class="card reverse-panel"><div class="row"><h2>反向解碼・動畫教室</h2><span class="tag">二補碼 → 十進制</span></div><p>負數的還原次序：先取反 → 再加 1 → 計算絕對值 → 加回負號。修改上方位元串後，按「解碼」即可更新這個示範。</p><div class="controls"><button class="button secondary" data-reverse-example="11100011">負數：1110 0011</button><button class="button secondary" data-reverse-example="01000011">正數：0100 0011</button><button class="button secondary" data-reverse-example="10000000">最小負數：1000 0000</button><label>播放速度<select id="reverse-speed"><option value="2500">正常（每步 2.5 秒）</option><option value="4000">慢速（每步 4 秒）</option><option value="1200">快速（每步 1.2 秒）</option></select></label></div><div id="reverse-error" class="error" role="alert"></div><div class="hex-scene"><div class="row"><b id="reverse-title"></b><span id="reverse-count" class="tag"></span></div><div id="reverse-scene" class="teach-scene"></div><div id="reverse-explain" class="hex-detail" aria-live="polite" aria-atomic="true"></div></div><div class="controls"><button id="reverse-play" class="button">▶ 播放動畫</button><button id="reverse-prev" class="button secondary">上一步</button><button id="reverse-next" class="button secondary">下一步</button><button id="reverse-reset" class="button secondary">↺ 重播</button></div></section>`}
function reverseRow(label,bits,active=-1){return `<div class="reverse-row"><b>${label}</b><div class="reverse-bits" style="--count:${bits.length}">${[...bits].map((b,i)=>`<span class="teach-digit ${active===i?'focus-bit':''}">${b}</span>`).join('')}</div></div>`}
function makeReverseFrames(input){if(!/^[01]+$/.test(input)||![4,8,16].includes(input.length))throw new Error('請在上方輸入剛好 4、8 或 16 個 0 / 1，再按「解碼」。');let frames=[],n=input.length,negative=input[0]==='1',magnitude=input;const add=(title,scene,text)=>frames.push({title,scene,text});add('① 確認字長與符號位',reverseRow('輸入的二補碼',input,0),`<p>共有 <b>${n} 位元</b>，最高位是 <b>${input[0]}</b>。</p><p>${negative?'最高位為 1，表示負數。先記住負號，再用「先取反，再加 1」求絕對值。':'最高位為 0，表示非負數。毋須取反或加 1，直接用權重法。'}</p>`);
if(negative){let current=[...input];for(let i=0;i<n;i++){current[i]=input[i]==='1'?'0':'1';add(`② 取反：第 ${i+1} 位`,reverseRow('原來的二補碼',input,i)+reverseRow('逐位取反',current.join(''),i),`<p>第 ${i+1} 位：<b>${input[i]} → ${current[i]}</b>。先把所有位元反轉。</p><p>取反完成後還要加 1，才能得到絕對值。</p>`)}const inverted=current.join('');add('③ 取反完成，準備加 1',reverseRow('取反結果',inverted)+reverseRow('加上 1','1'.padStart(n,'0')),'<p>從最右邊加 1；若本欄得到 10₂，寫 0，向左進 1。</p>');let carry=1;for(let i=n-1;i>=0&&carry;i--){const old=Number(current[i]),sum=old+carry;current[i]=String(sum%2);carry=Math.floor(sum/2);add(`④ 加 1：右起第 ${n-i} 位`,reverseRow('取反結果',inverted,i)+reverseRow('加 1 的過程',current.join(''),i),`<p><b>${old} + 1 = ${sum===2?'10₂':'1₂'}</b>。</p><p>${carry?'本欄寫 0，向左進 1；下一步處理左邊一欄。':'本欄寫 1，沒有進位；左邊其他位元不變。'}</p>`)}magnitude=current.join('');}
const unsigned=parseInt(magnitude,2),terms=[...magnitude].map((b,i)=>({b:+b,p:n-1-i,w:2**(n-1-i)}));let total=0;for(let i=0;i<n;i++){const term=terms[i];total+=term.b*term.w;add(`${negative?'⑤':'②'} 權重法：2 的 ${term.p} 次方`,reverseRow(negative?'絕對值（無符號）':'非負數',magnitude,i),`<p class="hex-calculation">${term.b} × 2<sup>${term.p}</sup> = ${term.b*term.w}</p><p>目前累計：<b>${total}</b>。</p>${negative?'<p>這一步按<b>無符號數值</b>計算絕對值；最高位的權重也是正數。</p>':''}`)}const value=negative?-unsigned:unsigned;add(negative?'⑥ 加回負號，解碼完成':'③ 解碼完成',reverseRow('原來的二補碼',input),`<p class="hex-calculation">${input}<sub>2</sub> → ${value}<sub>10</sub></p><p>${negative?`絕對值是 ${unsigned}，原來最高位為 1，所以答案是 <b>−${unsigned}</b>。`:`最高位為 0，因此答案是 <b>${unsigned}</b>。`}</p>${negative&&unsigned===2**(n-1)?`<div class="notice">特別留意：這裏的 ${magnitude} 按無符號方式計算絕對值 ${unsigned}。+${unsigned} 超出 ${n} 位元二補碼的正數範圍，但 −${unsigned} 可以表示。</div>`:''}`);return frames}
function loadReverse(){stopReverseAnimation();try{reverseFrames=makeReverseFrames(document.getElementById('decode').value.trim());reverseIndex=0;re('error').textContent='';renderReverse()}catch(e){re('error').textContent=e.message}}
function renderReverse(){let f=reverseFrames[reverseIndex];re('title').textContent=f.title;re('count').textContent=`${reverseIndex+1} / ${reverseFrames.length}`;re('scene').innerHTML=f.scene;re('explain').innerHTML=f.text;re('prev').disabled=reverseIndex===0;re('next').disabled=reverseIndex===reverseFrames.length-1;re('play').textContent=reversePlaying?'Ⅱ 暫停動畫':reverseIndex===reverseFrames.length-1?'▶ 再播一次':'▶ 播放動畫'}
function scheduleReverse(){reverseTimer=setTimeout(()=>{if(!reversePlaying||!re('scene')){stopReverseAnimation();return}reverseIndex++;if(reverseIndex===reverseFrames.length-1)stopReverseAnimation();renderReverse();if(reversePlaying)scheduleReverse()},Number(re('speed').value))}
function mountReverse(){document.getElementById('decodego').onclick=()=>{decode();loadReverse()};document.getElementById('decode').oninput=()=>{stopReverseAnimation();re('error').textContent='位元串已修改，請按上方「解碼」更新示範。'};document.querySelectorAll('[data-reverse-example]').forEach(b=>b.onclick=()=>{document.getElementById('decode').value=b.dataset.reverseExample;decode();loadReverse()});re('play').onclick=()=>{if(reversePlaying){stopReverseAnimation();return}stopTeachingAnimation();if(reverseIndex===reverseFrames.length-1)reverseIndex=0;reversePlaying=true;renderReverse();scheduleReverse()};re('prev').onclick=()=>{stopReverseAnimation();reverseIndex=Math.max(0,reverseIndex-1);renderReverse()};re('next').onclick=()=>{stopReverseAnimation();reverseIndex=Math.min(reverseFrames.length-1,reverseIndex+1);renderReverse()};re('reset').onclick=()=>{stopReverseAnimation();stopTeachingAnimation();reverseIndex=0;reversePlaying=true;renderReverse();scheduleReverse()};re('speed').onchange=()=>{if(reversePlaying){clearTimeout(reverseTimer);scheduleReverse()}};loadReverse()}
